#!/usr/bin/env python

import os
import sys
import argparse
import subprocess
sys.path.append('../src')

import numpy as np
import pandas as pd
import pickle

import iodata
import models


if __name__ != '__main__':
    sys.exit()

desc = """ 
       """

# Describe the arguments into the program. 
parser = argparse.ArgumentParser(description=desc)
parser.add_argument('-t', '--title', type=str, default='', 
                    help='The description of the mcmc experiment. This is going to be \
                          the name of directory to be saved.')
parser.add_argument('-o', '--outputdir', type=str, default='../results/pde_simulation', 
                    help='The path to the directory where results are saved.')
parser.add_argument('-pf', '--prefecture', type=str, default='Tokyo', 
                    help='The prefecture for which modeling is going to be conducted.')
parser.add_argument('-n', '--npoints', type=int, 
                    help='Number of points in space in PDE.')
parser.add_argument('-dc', '--diffusion-coefficient', type=float, 
                    help='Diffusion coefficient in diffusion equations.')
parser.add_argument('-l', '--length', type=float, 
                    help='Upper limit of space (lower limit: 0).')
parser.add_argument('-sp', '--sampler-path', type=str, default='../results/sampler', 
                    help='The path to the directory where samplers in each experiment \
                          is saved.')
parser.add_argument('-d', '--discard', type=int, default=0, 
                    help='Discard the first "discard" steps in the chain as burn-in.')
parser.add_argument('-tn', '--thin', type=int, default=1, 
                    help='Use only every "thin" steps from the chain')
parser.add_argument('-p', '--parameter', type=str, 
                    help='How to choose parameter sets. sampler (median/mean/mode) or parameters (given)')
parser.add_argument('-prp', '--parameter-path', type=str, default=None, 
                    help='The path to the sampler or parameters.')
parser.add_argument('-pm', '--parameter-method', type=str, default='median', 
                    help='How to determine the representative parameter set from \
                          MCMC sampler. median / mean')
parser.add_argument('-fd', '--first-day', type=int, default=0, 
                    help='The first day from which modeling is going to be conducted.')
parser.add_argument('-ld', '--last-day', type=int, default=50, 
                    help='The last day from which modeling is going to be conducted.')
parser.add_argument('-fdf', '--first-day-fitting', type=int, default=None, 
                    help='The first day from which fitting is going to be conducted.')
parser.add_argument('-ldf', '--last-day-fitting', type=int, default=None, 
                    help='The last day from which fitting is going to be conducted.')
parser.add_argument('-os', '--ode-step', type=int, default=1000, 
                    help='The resolution of a solution of ODEs.')
parser.add_argument('-ppp', '--population-path', type=str, default='../data/population.csv', 
                    help='The path to the population data for each prefecture.')
parser.add_argument('-dd', '--distance-dir', type=str, 
                    help='The name of directory where distance pickle files are saved.')
parser.add_argument('-s', '--simulation', type=str, 
                    help='Designate the simulation to be conducted. population/distance/both')
parser.add_argument('-cf', '--coefficient', type=int, default=0, 
                    help='The log-scale coefficient of the parameter to be simulated (coef=10**(cf/cf_div)).')
parser.add_argument('-cfd', '--coefficient_div', type=int, default=10, 
                    help='The log-scale coefficient of the parameter to be simulated (coef=10**(cf/cf_div)).')

# Pull the arguments
args = parser.parse_args()

# Define t (mesh points in time)
duration = args.last_day - args.first_day
t = np.linspace(0, duration, duration*args.ode_step+1)

# Define fitting period
ini = args.first_day_fitting - args.first_day
ter = args.last_day_fitting - args.first_day
t2 = np.linspace(ini, ter, (ter-ini)*args.ode_step+1)

# Define model
population = iodata.load_population(args.population_path, args.prefecture)
model = models.SeirPdeSimulation(
    prefecture=args.prefecture, 
    population=population, 
)

# Load sampler and extract representative parameters
if args.parameter == 'parameters':
    with open(args.parameter_path, 'rb') as f:
        parameters = pickle.load(f) # beta, epsilon, rho, xi, e0, i0, tau

elif args.parameter == 'sampler':
    if args.parameter_path is None:
        filename = f'{args.prefecture}.pickle'
        param_path = os.path.join(args.sampler_path, args.title, filename)
    else:
        param_path = args.parameter_path
    with open(param_path, 'rb') as f:
        sampler = pickle.load(f)
    flat_samples = sampler.get_chain(discard=args.discard, thin=args.thin, flat=True)
    parameters = getattr(np, args.parameter_method)(flat_samples, axis=0)

n = args.npoints
D = args.diffusion_coefficient
L = args.length
diffusion_parameters = np.array([n, D, L])
theta = np.append(diffusion_parameters, parameters)

# Solve PDE
cf = args.coefficient / args.coefficient_div
i = model.solve(theta, t, t2, cf=cf)
if args.coefficient != 0:
    i_ = model.solve(theta, t, t2, cf=-cf)

# Save solution
save_file = f'day{args.first_day_fitting}-{args.last_day_fitting}_cf{cf}'
savedir = os.path.join(args.outputdir, f'{args.title}')
subprocess.run(['mkdir', '-p', savedir])
with open(os.path.join(savedir, f'{save_file}.pickle'), mode='wb') as f:
    pickle.dump(i, f)
if args.coefficient != 0:
    with open(os.path.join(savedir, f'{save_file}-.pickle'), mode='wb') as f:
        pickle.dump(i_, f)
